root = "."
tmp_dir = "tmp"

[build]
# バイナリファイルを生成するコマンド
cmd = "go build -o ./tmp/main ./cmd/server/main.go"
# 監視対象のファイル
include_ext = ["go", "tpl", "tmpl", "html"]
# 監視から除外するディレクトリ
exclude_dir = ["assets", "tmp", "vendor", ".git", ".postgres"]
# 監視から除外するファイル
exclude_file = []
# 監視を停止する正規表現
exclude_regex = ["_test.go"]
# シャットダウン時に一時ファイルを削除
clean_on_exit = true

[screen]
clear_on_rebuild = true

[log]
# ログの詳細レベル
time = false

[color]
# ビルド結果の色付け
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# ファイル変更後のビルド遅延
clean_on_exit = true