services:
  db:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: wakabatasks
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:10.15.2
    container_name: flyway
    command: -url=jdbc:postgresql://db:5432/wakabatasks -user=exampleuser -password=examplepass migrate
    depends_on:
      - db
    volumes:
      - ./flyway/sql:/flyway/sql
