[tools]
go = "1.24.4"
golangci-lint = "2.1.6"

[tasks.run]
description = 'go run'
run = 'go run ./cmd/server/main.go'

[tasks.lint]
description = 'golangci-lint run'
run = 'go run ./cmd/server/main.go'
