// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAccessToken = "access_tokens"

// AccessToken mapped from table <access_tokens>
type AccessToken struct {
	ID         string     `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID     string     `gorm:"column:user_id;not null" json:"user_id"`
	TokenHash  string     `gorm:"column:token_hash;not null" json:"token_hash"`
	IssuedAt   time.Time  `gorm:"column:issued_at;not null;default:now()" json:"issued_at"`
	ExpiresAt  time.Time  `gorm:"column:expires_at;not null" json:"expires_at"`
	RevokedAt  *time.Time `gorm:"column:revoked_at" json:"revoked_at"`
	ClientInfo *string    `gorm:"column:client_info" json:"client_info"`
	CreatedAt  time.Time  `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt  time.Time  `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName AccessToken's table name
func (*AccessToken) TableName() string {
	return TableNameAccessToken
}
