// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthProvider = "auth_providers"

// AuthProvider mapped from table <auth_providers>
type AuthProvider struct {
	ID             string     `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID         string     `gorm:"column:user_id;not null" json:"user_id"`
	Provider       string     `gorm:"column:provider;not null" json:"provider"`
	ProviderUserID string     `gorm:"column:provider_user_id;not null" json:"provider_user_id"`
	CreatedAt      *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;default:now()" json:"updated_at"`
}

// TableName AuthProvider's table name
func (*AuthProvider) TableName() string {
	return TableNameAuthProvider
}
