// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmailVerificationToken = "email_verification_tokens"

// EmailVerificationToken mapped from table <email_verification_tokens>
type EmailVerificationToken struct {
	ID        string     `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID    string     `gorm:"column:user_id;not null" json:"user_id"`
	TokenHash string     `gorm:"column:token_hash;not null" json:"token_hash"`
	ExpiresAt time.Time  `gorm:"column:expires_at;not null" json:"expires_at"`
	UsedAt    *time.Time `gorm:"column:used_at" json:"used_at"`
	CreatedAt *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName EmailVerificationToken's table name
func (*EmailVerificationToken) TableName() string {
	return TableNameEmailVerificationToken
}
