// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRefreshToken = "refresh_tokens"

// RefreshToken mapped from table <refresh_tokens>
type RefreshToken struct {
	ID        string     `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID    string     `gorm:"column:user_id;not null" json:"user_id"`
	TokenHash string     `gorm:"column:token_hash;not null" json:"token_hash"`
	ExpiresAt time.Time  `gorm:"column:expires_at;not null" json:"expires_at"`
	CreatedAt *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	RevokedAt *time.Time `gorm:"column:revoked_at" json:"revoked_at"`
}

// TableName RefreshToken's table name
func (*RefreshToken) TableName() string {
	return TableNameRefreshToken
}
