// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskTag = "task_tags"

// TaskTag mapped from table <task_tags>
type TaskTag struct {
	ID     string `gorm:"column:id;primaryKey" json:"id"`
	TaskID string `gorm:"column:task_id" json:"task_id"`
	TagID  string `gorm:"column:tag_id" json:"tag_id"`
}

// TableName TaskTag's table name
func (*TaskTag) TableName() string {
	return TableNameTaskTag
}
