// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWebauthnCredential = "webauthn_credentials"

// WebauthnCredential mapped from table <webauthn_credentials>
type WebauthnCredential struct {
	ID           string     `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID       string     `gorm:"column:user_id;not null" json:"user_id"`
	CredentialID string     `gorm:"column:credential_id;not null" json:"credential_id"`
	PublicKey    string     `gorm:"column:public_key;not null" json:"public_key"`
	SignCount    *int64     `gorm:"column:sign_count" json:"sign_count"`
	CreatedAt    *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	UpdatedAt    *time.Time `gorm:"column:updated_at;default:now()" json:"updated_at"`
}

// TableName WebauthnCredential's table name
func (*WebauthnCredential) TableName() string {
	return TableNameWebauthnCredential
}
