ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN id SET NOT NULL;

ALTER TABLE projects ALTER COLUMN id DROP DEFAULT;
ALTER TABLE projects ALTER COLUMN id SET NOT NULL;

ALTER TABLE tasks ALTER COLUMN id DROP DEFAULT;
ALTER TABLE tasks ALTER COLUMN id SET NOT NULL;

ALTER TABLE task_comments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE task_comments ALTER COLUMN id SET NOT NULL;

ALTER TABLE tags ALTER COLUMN id DROP DEFAULT;
ALTER TABLE tags ALTER COLUMN id SET NOT NULL;

ALTER TABLE task_tags ALTER COLUMN id DROP DEFAULT;
ALTER TABLE task_tags ALTER COLUMN id SET NOT NULL;
